// Merchant/src/components/Sidebar.vue
<template>
  <div 
    class="fixed inset-y-0 left-0 z-50 flex flex-col bg-background border-r border-border transition-all duration-300"
    :class="[isCollapsed ? 'w-20' : 'w-64', isMobile && !mobileOpen ? '-translate-x-full' : 'translate-x-0']"
  >
    <!-- Header -->
    <div class="h-16 flex items-center border-b border-border" :class="isCollapsed ? 'justify-center px-2' : 'justify-between px-4'">
      <div class="flex items-center gap-2 relative" :class="isCollapsed ? 'justify-center' : 'overflow-hidden'">
        <transition name="logo-transition" mode="out-in">
          <img 
            v-if="isCollapsed" 
            key="icon"
            src="/blinkpe-icon.png" 
            alt="BlinkPe" 
            class="h-9 w-9 object-contain shrink-0" 
          />
          <img 
            v-else
            key="full"
            src="/blinkpe-logo.png" 
            alt="BlinkPe" 
            class="h-8 w-auto object-contain shrink-0" 
          />
        </transition>
      </div>
      <button 
        @click="toggleCollapse"
        class="hidden md:block p-2 rounded-md hover:bg-muted text-muted-foreground transition-colors"
      >
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M15 18l-6-6 6-6" v-if="!isCollapsed"/>
          <path d="M9 18l6-6-6-6" v-else/>
        </svg>
      </button>
      <button 
        @click="$emit('close-mobile')"
        class="md:hidden p-2 rounded-md hover:bg-muted text-muted-foreground transition-colors"
      >
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M18 6L6 18M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 overflow-y-auto py-4 px-3 space-y-1">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 px-3 py-2 rounded-md transition-colors group relative"
        :class="isActive(item.path) ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'"
        @click="isMobile && $emit('close-mobile')"
      >
        <component :is="item.icon" class="w-5 h-5 shrink-0" />
        <span 
          v-if="!isCollapsed" 
          class="text-sm font-medium whitespace-nowrap"
        >{{ item.label }}</span>
        
        <!-- Tooltip for collapsed state -->
        <div 
          v-if="isCollapsed && !isMobile" 
          class="absolute left-full ml-2 px-2 py-1 bg-popover text-popover-foreground text-xs rounded shadow-md opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-50"
        >
          {{ item.label }}
        </div>
      </router-link>
    </nav>

    <!-- User Footer -->
    <div class="p-4 border-t border-border relative">
      <button 
        @click="toggleUserMenu"
        class="flex items-center gap-3 w-full hover:bg-accent rounded-md p-2 transition-colors"
      >
        <div class="w-9 h-9 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center text-sm font-medium text-white shrink-0">
          {{ userInitials }}
        </div>
        <div v-if="!isCollapsed" class="min-w-0 flex-1 text-left">
          <div class="text-sm font-medium text-foreground truncate">{{ userName }}</div>
          <div class="text-xs text-muted-foreground truncate">{{ userEmail }}</div>
        </div>
        <svg v-if="!isCollapsed" class="h-4 w-4 text-muted-foreground shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="m6 9 6 6 6-6" />
        </svg>
      </button>

      <!-- User Dropdown Menu -->
      <div
        v-if="showUserMenu"
        class="absolute bottom-full left-4 right-4 mb-2 rounded-lg border bg-popover p-1 text-popover-foreground shadow-lg z-50"
      >
        <button
          @click="goToSettings"
          class="relative flex w-full cursor-pointer select-none items-center rounded-sm px-2 py-2 text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground"
        >
          <svg class="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="3" />
            <path d="M12 1v6m0 6v6M1 12h6m6 0h6M4.22 4.22l4.24 4.24m5.08 5.08l4.24 4.24M19.78 4.22l-4.24 4.24m-5.08 5.08l-4.24 4.24" />
          </svg>
          Profile
        </button>

        <button
          @click="router.push('/settings'); showUserMenu = false"
          class="relative flex w-full cursor-pointer select-none items-center rounded-sm px-2 py-2 text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground"
        >
          <svg class="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
             <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.1a2 2 0 0 1-1-1.72v-.51a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
             <circle cx="12" cy="12" r="3" />
          </svg>
          Settings
        </button>

        <div class="h-px bg-border my-1"></div>

        <button
          @click="handleLogout"
          class="relative flex w-full cursor-pointer select-none items-center rounded-sm px-2 py-2 text-sm outline-none transition-colors hover:bg-destructive/10 text-destructive"
        >
          <svg class="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9" />
          </svg>
          Logout
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile Overlay -->
  <div 
    v-if="isMobile && mobileOpen" 
    @click="$emit('close-mobile')"
    class="fixed inset-0 bg-background/80 backdrop-blur-sm z-40 md:hidden"
  ></div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { session } from '@/data/session'
import { 
  LayoutDashboard, 
  ShoppingBag, 
  BookOpen, 
  FileText, 
  Settings,
  CreditCard,
  Code
} from 'lucide-vue-next'

const props = defineProps({
  mobileOpen: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['close-mobile'])

const navItems = [
  { path: '/', label: 'Dashboard', icon: LayoutDashboard },
  { path: '/orders', label: 'Orders', icon: ShoppingBag },
  { path: '/virtual-accounts', label: 'Virtual Accounts', icon: CreditCard },
  { path: '/ledger', label: 'Ledger', icon: BookOpen },
  { path: '/wallet', label: 'Wallet', icon: FileText },
  { path: '/developers', label: 'Developers', icon: Code },
]

const route = useRoute()
const router = useRouter()
const isCollapsed = ref(false)
const isMobile = ref(false)
const showUserMenu = ref(false)

const userName = computed(() => session.user || 'User')
const userEmail = computed(() => session.user || 'user@example.com')
const userInitials = computed(() => {
  const name = userName.value
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
})

const isActive = (path) => {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}

const toggleCollapse = () => {
  isCollapsed.value = !isCollapsed.value
}

const checkMobile = () => {
  isMobile.value = window.matchMedia('(max-width: 768px)').matches
  if (!isMobile.value) {
    isCollapsed.value = false
  }
}

const toggleUserMenu = () => {
  showUserMenu.value = !showUserMenu.value
}

const goToSettings = () => {
  router.push('/profile')
  showUserMenu.value = false
  if (isMobile.value) {
    emit('close-mobile')
  }
}

const handleLogout = () => {
  session.logout.submit()
  showUserMenu.value = false
}

const handleClickOutside = (event) => {
  if (showUserMenu.value) {
    const userSection = event.target.closest('.p-4.border-t')
    if (!userSection) {
      showUserMenu.value = false
    }
  }
}

onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  window.removeEventListener('resize', checkMobile)
  document.removeEventListener('click', handleClickOutside)
})
</script>

<style scoped>
.logo-transition-enter-active,
.logo-transition-leave-active {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.logo-transition-enter-from {
  opacity: 0;
  transform: scale(0.9);
}

.logo-transition-leave-to {
  opacity: 0;
  transform: scale(0.9);
}

.logo-transition-enter-to,
.logo-transition-leave-from {
  opacity: 1;
  transform: scale(1);
}
</style>

// portal/src/components/layout/Sidebar.tsx
import { NavLink, useLocation } from 'react-router-dom';
import {
  LayoutDashboard, ArrowLeftRight, ShoppingCart, BookOpen, FileText,
  Code, Settings, ChevronDown,
  Building2, Wallet, BarChart3
} from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../../hooks';

interface SidebarProps {
  isAdmin?: boolean;
  isOpen?: boolean;
  onClose?: () => void;
}

interface NavItem {
  name: string;
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  children?: { name: string; href: string }[];
}

const merchantNavItems: NavItem[] = [
  { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
  // { name: 'Transactions', href: '/transactions', icon: ArrowLeftRight },
  { name: 'Orders', href: '/orders', icon: ShoppingCart },
  { name: 'Ledger', href: '/ledger', icon: BookOpen },
  { name: 'Settlements', href: '/settlements', icon: Wallet },
  { name: 'Deposit Funds', href: '/wallet/deposit', icon: Building2 },
  { name: 'Developers', href: '/developers', icon: Code },
  {
    name: 'Settings',
    href: '/settings',
    icon: Settings,
    children: [
      { name: 'Profile', href: '/settings/profile' },
      { name: 'Team', href: '/settings/team' },
      { name: 'Security', href: '/settings/security' },
      // { name: 'Notifications', href: '/settings/notifications' },
      { name: 'KYC', href: '/settings/kyc' },
    ],
  },
];

const adminNavItems: NavItem[] = [
  { name: 'Dashboard', href: '/admin/dashboard', icon: LayoutDashboard },
  { name: 'Merchants', href: '/admin/merchants', icon: Building2 },
  { name: 'Orders', href: '/admin/orders', icon: ShoppingCart },
  { name: 'KYC Reviews', href: '/admin/kyc-reviews', icon: FileText },
  { name: 'Reports', href: '/admin/reports', icon: BarChart3 },
  // { name: 'Transactions', href: '/admin/transactions', icon: ArrowLeftRight },
  // Temporarily disabled - not implemented with real APIs:
  // { name: 'Risk Alerts', href: '/admin/risk-alerts', icon: AlertTriangle },
  // { name: 'Users', href: '/admin/users', icon: Users },
  { name: 'Settlements', href: '/admin/van-logs', icon: Wallet },
  { name: 'Virtual Accounts', href: '/admin/virtual-accounts', icon: Building2 },
  { name: 'Settings', href: '/admin/settings', icon: Settings },
];

function NavItemComponent({ item }: { item: NavItem; isAdmin: boolean }) {
  const location = useLocation();
  const [isOpen, setIsOpen] = useState(
    item.children?.some(child => location.pathname.startsWith(child.href)) || false
  );

  const isActive = location.pathname === item.href ||
    (item.children && item.children.some(child => location.pathname.startsWith(child.href)));

  if (item.children) {
    return (
      <div>
        <button
          onClick={() => setIsOpen(!isOpen)}
          className={`
            w-full flex items-center justify-between px-3 py-2 text-sm font-medium rounded-lg
            transition-colors duration-150
            ${isActive ? 'text-slate-900 bg-slate-100' : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'}
          `}
        >
          <div className="flex items-center gap-3">
            <item.icon className="w-5 h-5" />
            {item.name}
          </div>
          <ChevronDown className={`w-4 h-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
        </button>
        {isOpen && (
          <div className="mt-1 ml-8 space-y-1">
            {item.children.map(child => (
              <NavLink
                key={child.href}
                to={child.href}
                className={({ isActive }) => `
                  block px-3 py-2 text-sm rounded-lg transition-colors duration-150
                  ${isActive
                    ? 'text-slate-900 bg-slate-100 font-medium'
                    : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
                  }
                `}
              >
                {child.name}
              </NavLink>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <NavLink
      to={item.href}
      className={({ isActive }) => `
        flex items-center gap-3 px-3 py-2 text-sm font-medium rounded-lg
        transition-colors duration-150
        ${isActive
          ? 'text-slate-900 bg-slate-100'
          : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
        }
      `}
    >
      <item.icon className="w-5 h-5" />
      {item.name}
    </NavLink>
  );
}

export function Sidebar({ isAdmin = false, isOpen = false, onClose }: SidebarProps) {
  const { user } = useAuth();

  // Filter navigation items based on role
  let navItems = isAdmin ? adminNavItems : merchantNavItems;

  if (!isAdmin && user?.merchant?.role && user.merchant.role !== 'Owner') {
    navItems = navItems.map(item => {
      if (item.name === 'Settings' && item.children) {
        return {
          ...item,
          children: item.children.filter(child => child.name !== 'KYC')
        };
      }
      return item;
    });
  }

  // Get merchant info from auth context
  const merchant = !isAdmin && user?.merchant ? {
    businessName: user.merchant.company_name || 'Merchant',
    isLive: user.merchant.status === 'Active',
    logo: user.merchant.logo
  } : null;

  return (
    <>
      {/* Mobile Backdrop */}
      <div
        className={`fixed inset-0 z-40 bg-slate-900/50 backdrop-blur-sm lg:hidden transition-opacity duration-300 ${isOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
        onClick={onClose}
      />

      <aside className={`
        fixed left-0 top-0 z-50 h-screen w-64 bg-white border-r border-slate-200 transition-transform duration-300 ease-in-out
        ${isOpen ? 'translate-x-0' : '-translate-x-full'}
        lg:translate-x-0 lg:z-40
      `}>
        <div className="flex flex-col h-full">
          <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200">
            <div className="flex items-center gap-2">
              {user?.appLogo ? (
                <img
                  src={user.appLogo}
                  alt={user?.appName || "Logo"}
                  className="h-11 w-auto object-contain"
                />
              ) : (
                <div className="text-2xl font-bold text-primary-600">
                  {user?.appName || 'iSwitch'}
                </div>
              )}
              {isAdmin && (
                <span className="ml-2 text-xs bg-slate-900 text-white px-1.5 py-0.5 rounded">Admin</span>
              )}
            </div>
          </div>

          {!isAdmin && merchant && (
            <div className="px-4 py-4 border-b border-slate-200">
              <div className="flex items-center gap-3 px-2">
                <div className="w-9 h-9 bg-primary-100 rounded-lg flex items-center justify-center overflow-hidden">
                  {merchant.logo ? (
                    <img src={merchant.logo} alt={merchant.businessName} className="w-full h-full object-cover" />
                  ) : (
                    <Building2 className="w-5 h-5 text-primary-600" />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-slate-900 truncate">{merchant.businessName}</p>
                  <p className="text-xs text-slate-500">
                    {user?.user.email}
                  </p>
                </div>
              </div>
            </div>
          )}

          <nav className="flex-1 overflow-y-auto px-4 py-4 space-y-1 scrollbar-thin">
            {navItems.map(item => (
              <NavItemComponent key={item.href} item={item} isAdmin={isAdmin} />
            ))}
          </nav>
        </div>
      </aside>
    </>
  );
}
